# version string format
version: "{build}"

image: Visual Studio 2013
  
# clone directory
clone_folder: C:\projects\polylineencoder

init:
    - git config --global core.autocrlf input
  
# branches to build
branches:
    # whitelist
    only:
        - master

platform:
    - Win32
    - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
    - Debug
    - Release

build_script:
    - call "c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
    - cd C:\projects\polylineencoder\test
    - cl /EHsc main.cpp

test_script:
  - cd C:\projects\polylineencoder\test
  - main.exe