# version string format
version: "{build}"

image: Visual Studio 2017

# clone directory
clone_folder: C:\projects\polylineencoder

init:
    - git config --global core.autocrlf input

# branches to build
branches:
    # whitelist
    only:
        - master

platform:
    - Win32
    - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
    - Debug
    - Release

build_script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - cd %APPVEYOR_BUILD_FOLDER%
    - mkdir build
    - cd build

    # Build the GTest
    - git clone --branch release-1.10.0 https://github.com/google/googletest.git
    - cd googletest
    - mkdir build && cd build
    - cmake .. -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DCMAKE_INSTALL_PREFIX:PATH=. -G "NMake Makefiles"
    - nmake
    - nmake install

    # Configure CMake to find the GTest.
    - set CMAKE_PREFIX_PATH=%APPVEYOR_BUILD_FOLDER%\build\googletest\build

    - cd %APPVEYOR_BUILD_FOLDER%\build
    - cmake .. -G "NMake Makefiles"
    - nmake

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%\build
    - poly_test
